[workspace]

# Crates
# - core
# - loom-proto
# - loom-audio
# Apps
# - apps/voice_agent

members = [
    "core",
    "loom-proto",
    "loom-audio",
    "apps/voice_agent",
    "bridge",
]
resolver = "2"

[workspace.package]
edition = "2021"
